### ISSUE TITLE
ERROR in SchemaFormModule is not an NgModule

### ISSUE THREAD

**Issue by alimohammad** [makinacorpus/angular2-schema-form#48]
I am trying to use angular2-schema-form with the latest version of angular-cli.

When I am doing npm start then I am getting this issue : **ERROR in SchemaFormModule is not an NgModule**

I have checked the issue with angular-cli forums and it is happening with a lot of other modules, and according to what I understood on the forums the angular2 packages in angular2-schema-form need to be updated as well to make it usable with cli projects.

**My Angular2-Cli setup:**
angular-cli: 1.0.0-beta.24
node: 7.2.1
os: win32 x64
@angular/common: 2.4.1
@angular/compiler: 2.4.1
@angular/core: 2.4.1
@angular/forms: 2.4.1
@angular/http: 2.4.1
@angular/platform-browser: 2.4.1
@angular/platform-browser-dynamic: 2.4.1
@angular/router: 3.4.1
@angular/compiler-cli: 2.4.1

What are your suggestions ?

**Comment by ebrehault** [comment]
did you use the npm release or the GitHub checkout?

**Comment by Ragularuban** [comment]
#50 
As per https://github.com/angular/angular/issues/11262#issuecomment-244472000

> All referenced libraries must include the *.metadata.json file along side any *.d.ts files they produce…

I found an article for the solution - https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.np4jova1d

**Comment by alimohammad** [comment]
I used the npm release package.

**Comment by ebrehault** [comment]
I have just published 1.0.0-alpha.33, it should be better.

**Comment by Ragularuban** [comment]
I uninstalled angular2-schema form and installed the latest@1.0.0-alpha.33 again.

I still get the following error

-------------------------------------------------------------
[00:25:27]  ionic-app-scripts 0.0.47
[00:25:27]  build prod started ...
[00:25:27]  clean started ...
[00:25:27]  clean finished in 1 ms
[00:25:27]  copy started ...
[00:25:27]  ngc started ...
[00:25:29]  build prod failed: Unexpected value 'SchemaFormModule' imported by the module 'AppModule'
[00:25:29]  ionic-app-script task: "build"
[00:25:29]  Error: Unexpected value 'SchemaFormModule' imported by the module 'AppModule'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.5
-------------------------------------------------------------

I still dont see the *metadata.json file in the @1.0.0-alpha.33 release

**Comment by alimohammad** [comment]
@Ragularuban try importing modules from **src** by **import { SchemaFormModule, WidgetRegistry, DefaultWidgetRegistry } from "angular2-schema-form/src"** in case metadata file is not there.

It might work.

**Comment by SBats** [comment]
I didn't plan the AOT compatibility at all when I submitted the new structure.
I'm currently working on it in a branch and will do a PR soon.
Sorry for the inconvenience!

**Comment by Ragularuban** [comment]
@alimohammad it still didn't work. the issue was AOT compatibility

@SBats Thanks :-) Much Appreciate it.

**Comment by SBats** [comment]
Hey @alimohammad and @Ragularuban , could you please try with the last commit of this branch and let me know if it's any better?
https://github.com/SBats/angular2-schema-form/tree/fix-aot
If it works I'll PR it, merge and publish for a good npm version

**Comment by Ragularuban** [comment]
@SBats . Extremely sorry for the delay. I will update you on it very soon

**Comment by Ragularuban** [comment]
@SBats Please assist me...

1) git clone -g fix-aot https://github.com/SBats/angular2-schema-form.git
2)npm install
npm install threw an error

> > angular2-schema-form@1.0.0-alpha.31 prepublish C:\Users\User\Desktop\test\angular2-schema-form
> > export NODE_ENV=production; npm run build
> 
> 'export' is not recognized as an internal or external command,
> operable program or batch file.

I think the error is beacause i'm running in windows. so i i continue it doing manually. I edited webpack.config.js to run in production then i continue with 

3)npm run build
It threw the below errors

> > angular2-schema-form@1.0.0-alpha.31 copy-template C:\Users\User\Desktop\test\angular2-schema-form
> > copy ./src/**/*.html ./dist/src
> 
> The syntax of the command is incorrect.

I read npm copy documentation to find out that i need to wrap files names in quote. so I changed

> copy ./src/**/*.html ./dist/src

To

> copy "./src/**/*.html" "./dist/src"

and then ran the build...
 It threw the below error

> > angular2-schema-form@1.0.0-alpha.31 copy-template C:\Users\User\Desktop\test\angular2-schema-form
> > copy "./src/**/*.html" "./dist/src"
> 
> ./src/**/*.html
> The filename, directory name, or volume label syntax is incorrect.
>         0 file(s) copied.
> 

I tried various methods, but copy command is not letting me copy anything apart from the root directory(Weird)

Finally, i decided to to replace the 'copy' module with 'copyfiles' module

> https://www.npmjs.com/package/copyfiles

the build then finished without any errors! :-)

I copied the files into my project files, when i tried to build the solution i got the below error

> [05:41:34]  ngc started ...
> [05:41:54]  typescript: ...cts/*****/node_modules/angular2-schema-form/dist/src/model/formproperty.d.ts, line: 1
>             Cannot find type definition file for 'core-js'.
> 
>        L1:  import { BehaviorSubject
> from 'rxjs/BehaviorSubject';
> [05:41:54]  ionic-app-script task: "build"        L2:  import 'rxjs/add/observable/combineLatest';
> 
> 
> [05:41:54]  Error: Failed to transpile TypeScript
> 

Please look into the above.

**Comment by SBats** [comment]
Okay, we're coming close I think.
You are right, I didn't plan windows compatibility. I've fixed scripts following what you used to resolve your windows issues, so it should be ok.
As to types of core-js missings, you should just have to install them as dev dependencies and it should work.

So to summarize:
- remove angular2-schema-form from your node_modules and your `package.json` for now.
- remove the `@typings` folder you add manualy. On recent build Typescript is able to automaticly fetch typings from node_modules. So if you have one missing, there's 99% chance you don't have it installed.
- install schema form via the command `npm i git+https://github.com/SBats/angular2-schema-form.git\#da7ac6dc990813943c717052e26d8f2a9010a644` (it install it directly in you project instead of having to copy files manualy). Add `-S` if you want it saved as a dependency
- go in `node_modules/angular2-schema-form`and run `npm run build`
- add missing types via `npm i -D @types/core-js`

With this, you should have a stable base to test if the new version works.
If not let me know and we'll keep searching what's wrong.
Good luck :)

**Comment by Ragularuban** [comment]
I tried to do do

> npm i git+https://github.com/SBats/angular2-schema-form.git\#da7ac6dc990813943c717052e26d8f2a9010a64

• It threw the below error...

> npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git+https://github.com/SBats/angular2-schema-f
> orm.git\ C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-SBats-angular2-schema-form-git-da7ac6dc990813943c717052e26d8f2a9010a644-6cf526c4
> npm ERR! Cloning into bare repository 'C:\Users\User\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-SBats-angular2-schema-form-git-da7ac6dc990813943c717052e26d8f2a9010a644-6cf
> 526c4'...
> npm ERR! fatal: Unable to find remote helper for 'git+https'

•  So, I downloaded the _"da7ac6dc990813943c717052e26d8f2a9010a64"_ commit manually to _node_modules/angular2-schema-form_
• _npm install_
• _npm run build_
• cd to my project root
• ionic build android --prod

It threw the initial error again

> [01:24:36]  ngc started ...
> [01:24:40]  build prod failed: Unexpected value 'SchemaFormModule' imported by the module 'AppModule'
> [01:24:40]  ionic-app-script task: "build"
> [01:24:40]  Error: Unexpected value 'SchemaFormModule' imported by the module 'AppModule'


**:-(**

**Comment by Ragularuban** [comment]
@SBats in package.json

`"copy-template": "copyfiles './src/**/*.html' './dist/src'",`

this command is not working properly. I tried 

`"copy-template": "copyfiles \"./src/**/*.html\" \"./dist\"",`

this seems to do the copy action properly (Something to do with single quote and double quote)

**Comment by SBats** [comment]
Okay. I'll try to setup a Windows in order to test those issues in the same context as you.
You're still trying to use it on an ionic2 project, right?

**Comment by Ragularuban** [comment]
Yes. Ionic 2.
```
Ionic Framework: 2.0.0-rc.4
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.47
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.2
OS Platform: Windows 7
```

**Comment by SBats** [comment]
At the moment, I can't make it work because of a conflict between core-js and typescript libraries loaded by Ionic 2. We might need to check if core-js is still needed for our module development.
I'm a bit busy at the moment but I will try to work on this.

**Comment by Ragularuban** [comment]
@SBats It surprisingly works now without any issues :-)

All I did was updated my ionic project....

**Comment by pete-wright** [comment]
Any updates on this? I'm getting this same error after installing via npm on the angular4 release. I'm also on Windows and I've tried to work through the steps above but I'm still unable to get this working

**Comment by ebrehault** [comment]
It should be fixed with 1.0.0-beta.1

**Comment by Ragularuban** [comment]
I didn't check it personally, But one of my colleagues reported that AOT compilation is successful.

Thanks a lot team :-) @ebrehault @SBats

**Comment by ebrehault** [comment]
You are welcome!
We also have to mention @fbessou who is doing great job here!
